@startuml Code

start

    :Построить модель кодирования;
    :Установить low = 0.0, high = 1.0;
    while (не конец входного потока) is (да)

        :Считать символ с входного потока в s;
        :range = high - low;
        :high = low + range * верхная_граница_для_символа(s);
        :low = low + range * нижняя_граница_для_символа(s);

    endwhile (нет)

    :Вывести low (результат кодирования);

stop

@enduml
