@startuml Decode

start

    :Получить модель кодирования и вещественное число number;

    while (декодирование на закончено) is (да)

        :Найти символ s, соответствущий number (по подыитервалам);
        :Вывести символ s в выходной поток;
        :range  =верхная_граница_для_символа(s) - нижняя_граница_для_символа(s);
        :number = (number - нижняя_граница_для_символа(s)) / range;

    endwhile (нет)

stop

@enduml
